//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.1432.
// 
namespace MinerWars.AppCode.Game.Trailer {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class MyTrailerXml {
        
        private string gameAnimationField;
        
        private string flyThroughOrCreditsAnimationField;
        
        private MyTrailerXmlAnimation[] animationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GameAnimation {
            get {
                return this.gameAnimationField;
            }
            set {
                this.gameAnimationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlyThroughOrCreditsAnimation {
            get {
                return this.flyThroughOrCreditsAnimationField;
            }
            set {
                this.flyThroughOrCreditsAnimationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Animation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MyTrailerXmlAnimation[] Animation {
            get {
                return this.animationField;
            }
            set {
                this.animationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MyTrailerXmlAnimation {
        
        private string nameField;
        
        private int timeStartInMillisecondsField;
        
        private bool timeStartInMillisecondsFieldSpecified;
        
        private int timeEndInMillisecondsField;
        
        private bool timeEndInMillisecondsFieldSpecified;
        
        private MyTrailerXmlAnimationShip[] shipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TimeStartInMilliseconds {
            get {
                return this.timeStartInMillisecondsField;
            }
            set {
                this.timeStartInMillisecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeStartInMillisecondsSpecified {
            get {
                return this.timeStartInMillisecondsFieldSpecified;
            }
            set {
                this.timeStartInMillisecondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int TimeEndInMilliseconds {
            get {
                return this.timeEndInMillisecondsField;
            }
            set {
                this.timeEndInMillisecondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeEndInMillisecondsSpecified {
            get {
                return this.timeEndInMillisecondsFieldSpecified;
            }
            set {
                this.timeEndInMillisecondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ship", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MyTrailerXmlAnimationShip[] Ship {
            get {
                return this.shipField;
            }
            set {
                this.shipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class MyTrailerXmlAnimationShip {
        
        private string filepathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Filepath {
            get {
                return this.filepathField;
            }
            set {
                this.filepathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.1432")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private MyTrailerXml[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MyTrailerXml")]
        public MyTrailerXml[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
