using System;
using System.Collections.Generic;
using VRage.CommonLib.Utils;
using Sandbox.Engine.Utils;
using Sandbox.Game.Entities;
using SysUtils.Utils;
using SysUtils;
using Sandbox;
using System.Reflection;
using Sandbox.CommonLib;

namespace Sandbox.Engine.Audio
{
    enum MyMusicTransitionEnum
    {
        //MainMenu,
        //Horror,
        Mystery,
        //LightFight,
        //TensionBeforeAnAction,
        CalmAtmosphere,
        HeavyFight,
        //Victory,
        SadnessOrDesperation,
        //StressOrTimeRush,
        //StealthAction,
        DesperateWithStress,
        //Special,
    }

    //  Add here every sound/cue we use in the game. You don't need to add it to other places, that is done automaticaly by LoadContent
    //  IMPORTANT: DO NOT USE MULTILINE COMMENTS OR REGIONS!
    public enum MySoundCuesEnum : short
    {
        None,

        ImpBulletHitGlass,
        ImpBulletHitMetal,
        ImpBulletHitRock,
        ImpBulletHitShip,
        ImpExpHitGlass,
        ImpExpHitMetal,
        ImpExpHitRock,
        ImpExpHitShip,
        ImpPlayerShipCollideMetal,
        ImpPlayerShipCollideRock,
        ImpPlayerShipCollideShip,
        ImpPlayerShipScrapeShipLoop,
        ImpRockCollideMetal,
        ImpRockCollideRock,
        ImpShipCollideMetal,
        ImpShipCollideRock,

        SfxFlareLoop01,
        SfxGeigerCounterHeavyLoop,

        VehToolCrusherDrillLoop2d,
        VehToolCrusherDrillLoop3d,
        VehToolCrusherDrillRelease2d,
        VehToolCrusherDrillRelease3d,

        WepAutocanonFire2d,
        WepAutocanonFire3d,
        WepAutocanonRel2d,
        WepAutocanonRel3d,
        WepBombExplosion,
        WepLargeShipAutocannonRotate,
        WepLargeShipAutocannonRotateRelease,
        WepMachineGunHighFire2d,
        WepMachineGunHighFire3d,
        WepMachineGunHighRel2d,
        WepMachineGunHighRel3d,
        WepMachineGunNormFire2d,
        WepMachineGunNormFire3d,
        WepMachineGunNormRel2d,
        WepMachineGunNormRel3d,
        WepMissileExplosion,
        WepMissileFly,
        WepMissileLaunch2d,
        WepMissileLaunch3d,
        WepSniperScopeZoomALoop,
        WepSniperScopeZoomRel,

        ArcPlayRunMetalLoop2d,
        ArcPlayRunRockLoop2d,
        ArcPlayRunMetalLoop3d,
        ArcPlayRunRockLoop3d,
        ArcPlayJump2d,
        ArcPlayJump3d,
        ArcPlayFallMetal2d,
        ArcPlayFallRock2d,
        ArcPlayFallMetal3d,
        ArcPlayFallRock3d,

        ArcPlayJetOn2d,
        ArcPlayJetOff2d,
        ArcPlayJetIdleLoop2d,
        ArcPlayJetOn3d,
        ArcPlayJetOff3d,
        ArcPlayJetIdleLoop3d,
        ArcPlayJetRunLoop2d,
        ArcPlayJetRunLoop3d,

        HudClick,
        HudUse,
        HudRotateBlock,
        HudPlaceBlock,
        HudDeleteBlock,
        HudColorBlock,
        HudMouseClick,
        HudMouseOver,

        ArcWepPlayRifleShotLoop2d,
        ArcWepPlayRifleShotLoop3d,
        ArcWepPlayRifleShotRel2d,
        ArcWepPlayRifleShotRel3d,

        ArcToolPlayDrillIdleEnd2d,
        ArcToolPlayDrillIdleEnd3d,
        ArcToolPlayDrillIdleLoop2d,
        ArcToolPlayDrillIdleLoop3d,
        ArcToolPlayDrillIdleStart2d,
        ArcToolPlayDrillIdleStart3d,
        ArcToolPlayDrillMetalLoop2d,
        ArcToolPlayDrillMetalLoop3d,
        ArcToolPlayDrillRockLoop2d,
        ArcToolPlayDrillRockLoop3d,

        ArcWepShipGatlingShotLoop2d,
        ArcWepShipGatlingShotLoop3d,
        ArcWepShipGatlingShotRel2d,
        ArcWepShipGatlingShotRel3d,
        ArcWepShipMissileFlyLoop3d,
        ArcWepShipSmallMissileShot2d,
        ArcWepShipSmallMissileShot3d,

        ArcWepPlayRifleImpMetal3d,
        ArcWepPlayRifleImpPlay3d,
        ArcWepPlayRifleImpRock3d,

        ArcWepShipGatlingImpMetal3d,
        ArcWepShipGatlingImpPlay3d,
        ArcWepShipGatlingImpRock3d,

        ArcShipSmNuclearSmOff2d,
        ArcShipSmNuclearSmOff3d,
        ArcShipSmNuclearSmOn2d,
        ArcShipSmNuclearSmOn3d,
        ArcShipSmNuclearSmRunLoop2d,
        ArcShipSmNuclearSmRunLoop3d,

        ArcPlaySprintMetalLoop2d,
        ArcPlaySprintMetalLoop3d,
        ArcPlaySprintRockLoop2d,
        ArcPlaySprintRockLoop3d,
        ArcPlayCrouchDwn2d,
        ArcPlayCrouchDwn3d,
        ArcPlayCrouchMetalLoop2d,
        ArcPlayCrouchMetalLoop3d,
        ArcPlayCrouchRockLoop2d,
        ArcPlayCrouchRockLoop3d,
        ArcPlayCrouchUp2d,
        ArcPlayCrouchUp3d,

        ArcPlayIronSightOff2d,
        ArcPlayIronSightOff3d,
        ArcPlayIronSightOn2d,
        ArcPlayIronSightOn3d,

        ArcSmShipLrgJetLoop2d,
        ArcSmShipLrgJetLoop3d,
        ArcSmShipSmJetLoop2d,
        ArcSmShipSmJetLoop3d,

        ArcShipLandGearOff3d,
        ArcShipLandGearOn3d,

        ArcToolShipDrillIdleLoop2d,
        ArcToolShipDrillIdleLoop3d,
        ArcToolShipDrillMetalLoop2d,
        ArcToolShipDrillMetalLoop3d,
        ArcToolShipDrillRockLoop2d,
        ArcToolShipDrillRockLoop3d,
        ArcToolShipDrillOn2d,
        ArcToolShipDrillOn3d,
        ArcToolShipDrillOff2d,
        ArcToolShipDrillOff3d,

        ArcWepSmallMissileExplShip2d,
        ArcWepSmallMissileExplShip3d,
        ArcWepSmallMissileExpl2d,
        ArcWepSmallMissileExpl3d,
        ArcWepSmallMissileExplPlay2d,
        ArcWepSmallMissileExplPlay3d,

        ArcImpMetalMetal3d,
        ArcImpPlayerRock3d,
        ArcImpPlayerMetal3d,
        ArcImpPlayerPlayer3d,
        ArcImpRockRock3d,
        ArcImpMetalRock3d,

        ArcToolPlayGrindMetalLoop2d,
        ArcToolPlayGrindMetalLoop3d,
        ArcToolPlayGrindIdleLoop2d,
        ArcToolPlayGrindIdleLoop3d,
        ArcToolPlayWeldIdleLoop2d,
        ArcToolPlayWeldIdleLoop3d,
        ArcToolPlayWeldMetalLoop2d,
        ArcToolPlayWeldMetalLoop3d,
        ArcToolPlayGrindOff2d,
        ArcToolPlayGrindOff3d,
        ArcToolPlayGrindOn2d,
        ArcToolPlayGrindOn3d,

        ArcBlockGravityGenLoop3d,
        ArcBlockGravityGenOff3d,
        ArcBlockGravityGenOn3d,
        ArcBlockRafineryLoop2d,
        ArcBlockRafineryLoop3d,
        ArcBlockRafineryOff2d,
        ArcBlockRafineryOff3d,
        ArcBlockRafineryOn2d,
        ArcBlockRafineryOn3d,

        ArcBlockAssemblerLoop2d,
        ArcBlockAssemblerLoop3d,
        ArcBlockAssemblerOff2d,
        ArcBlockAssemblerOff3d,
        ArcBlockAssemblerOn2d,
        ArcBlockAssemblerOn3d,

        ArcPlayJetRunStart2d,
        ArcPlayJetRunStart3d,
        ArcPlayJetRunRelease2d,
        ArcPlayJetRunRelease3d,

        ArcBlockMedicalProgressStart2d,
        ArcBlockMedicalProgressStart3d,
        ArcBlockMedicalLoop3d,
        ArcBlockMedicalProgressEnd2d,
        ArcBlockMedicalProgressEnd3d,
        ArcBlockMedicalProgressLoop2d,
        ArcBlockMedicalProgressLoop3d,

        ArcBlockReactorLrgLoop3d,
        ArcBlockReactorLrgOff3d,
        ArcBlockReactorLrgOn3d,
        ArcBlockReactorSmLoop3d,
        ArcBlockReactorSmOff3d,
        ArcBlockReactorSmOn3d,

        ArcSmShipSmJetStart2d,
        ArcSmShipSmJetStart3d,
        ArcSmShipLrgJetRelease2d,
        ArcSmShipLrgJetRelease3d,
        ArcSmShipLrgJetStart2d,
        ArcSmShipLrgJetStart3d,
        ArcSmShipSmJetRelease2d,
        ArcSmShipSmJetRelease3d,

        ArcBlockRotorIOff3d,
        ArcBlockRotorLoop3d,
        ArcBlockRotorIOn3d,

        ArcBlockRotorSmallLoop3d,
        ArcBlockRotorSmallOff3d,
        ArcBlockRotorSmallOn3d,

        ArcBlockRafineryProcessIntro2d,
        ArcBlockRafineryProcessIntro3d,
        ArcBlockRafineryProcessOutro3d,
        ArcBlockRafineryProcessOutro2d,
        ArcBlockRafineryProcessLoop3d,
        ArcBlockRafineryProcessLoop2d,

        ArcBlockAssemblerProcessIntro2d,
        ArcBlockAssemblerProcessIntro3d,
        ArcBlockAssemblerProcessLoop2d,
        ArcBlockAssemblerProcessLoop3d,
        ArcBlockAssemblerProcessOutro3d,
        ArcBlockAssemblerProcessOutro2d,

        ArcBlockDoorSmallClose3d,
        ArcBlockDoorSmallOpen3d,

        ArcPlayDropItem2d,
        ArcPlayDropItem3d,
        ArcPlayTakeItem3d,

        ArcBlockCockpitLrgLoop2d,
        ArcBlockCockpitLrgLoop3d,

        ArcToolPlayGrindMetalIntro2d,
        ArcToolPlayGrindMetalIntro3d,
        ArcToolPlayGrindMetalOutro2d,
        ArcToolPlayGrindMetalOutro3d,

        ArcShipLrgNuclearSmRunLoop3d,
        ArcShipLrgNuclearSmRunLoop2d,
        ArcShipLrgNuclearSmOn3d,
        ArcShipLrgNuclearSmOn2d,
        ArcShipLrgNuclearSmOff3d,
        ArcShipLrgNuclearSmOff2d,
        ArcShipLrgNuclearLrgRunLoop3d,
        ArcShipLrgNuclearLrgRunLoop2d,
        ArcShipLrgNuclearLrgOn3d,
        ArcShipLrgNuclearLrgOn2d,
        ArcShipLrgNuclearLrgOff3d,
        ArcShipLrgNuclearLrgOff2d,

        ArcShipSmNuclearLrgRunLoop3d,
        ArcShipSmNuclearLrgRunLoop2d,
        ArcShipSmNuclearLrgOn3d,
        ArcShipSmNuclearLrgOn2d,
        ArcShipSmNuclearLrgOff3d,
        ArcShipSmNuclearLrgOff2d,

        HudUnable,

        ArcPrgConstrPh01Start3d,
        ArcPrgConstrPh02Proc3d,
        ArcPrgConstrPh03Fin3d,
        ArcPrgDeconstrPh01Start3d,
        ArcPrgDeconstrPh02Proc3d,
        ArcPrgDeconstrPh03Fin3d,

        ArcBlockCockpitSmLoop3d,
        ArcBlockCockpitSmLoop2d,

        HudVocAmmoCritical,
        HudVocAmmoLow,
        HudVocAmmoNo,
        HudVocHealthCritical,
        HudVocHealthLow,

        ArcPlayVocPain3d,

        MusCalmAtmosphere_KA01,
        MusCalmAtmosphere_KA02,
        MusCalmAtmosphere_KA03,
        MusCalmAtmosphere_KA05,
        MusCalmAtmosphere_MM_b,
        MusCalmAtmosphere_MM01,
        MusCalmAtmosphere_MM02,
        MusDesperateWithStress_KA01,
        MusDesperateWithStress_KA02,
        MusDesperateWithStress_KA03,
        MusDesperateWithStress_KA04,
        MusHeavyFight_KA01,
        MusHeavyFight_KA02,
        MusHeavyFight_KA03,
        MusHeavyFight_KA04,
        MusHeavyFight_KA05,
        MusHeavyFight_KA07,
        MusHeavyFight_KA15,
        MusMystery_KA01,
        MusMystery_KA02,
        MusSadnessOrDesperation_KA01,
        MusSadnessOrDesperation_KA02,
        MusSadnessOrDesperation_MM01,

        ArcShipLandGearNothing3d01,

        ArcWepShipGatlingNoAmmo3d,
        ArcWepPlayRifleNoAmmo3d,

        ArcPlayVocDeath3d,

        ArcLrgShipSmJetStart3d,
        ArcLrgShipSmJetLoop3d,
        ArcLrgShipLrgJetStart3d,
        ArcLrgShipLrgJetLoop3d,
    }
}
