#define RENDERING_PASS_GBUFFER 0
#define RENDERING_PASS_DEPTH 1
#define RENDERING_PASS_FORWARD 2
#define RENDERING_PASS_HIGHLIGHT 3
#define RENDERING_PASS_FOLIAGE_STREAMING 4
#define RENDERING_PASS_STATIC_GLASS 5 
#define RENDERING_PASS_TEST 100
